spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: dossier
mail:
  host: app.debugmail.io
  port: 25
  username: 6117424a-a520-464c-890b-87ab9bba81a8
  password: f0fce39d-6090-4743-844a-2513aaba82ff
  protocol: smtp
  ssl: false
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: app.debugmail.io
server:
  port: 8083

