spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: dossier
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: breskinaolya@gmail.com
#    password:
#    protocol: smtp
#    tls: true
#    properties.mail.smtp:
#      auth: true
#      starttls.enable: true
#      ssl.trust: smtp.gmail.com


